services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: earnVibe_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: earnVibe_postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        expose:
            - 5432

    pgadmin:
        image: dpage/pgadmin4
        container_name: earnVibe_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "9091:90"
        networks:
            - app-network

    web:
        container_name: earnVibe_web
        image: nginx:alpine
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    node:
        container_name: earnVibe_node
        image: node:20
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        command: bash -c "npm install && npm run build"

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
